// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNU4uGQRr9gWJQ1Vw2zEYgxw8oz3kNNHs',
    appId: '1:195576479889:web:887a21e706a400fb10bf30',
    messagingSenderId: '195576479889',
    projectId: 'kebab-and-ploff',
    authDomain: 'kebab-and-ploff.firebaseapp.com',
    databaseURL: 'https://kebab-and-ploff-default-rtdb.firebaseio.com',
    storageBucket: 'kebab-and-ploff.appspot.com',
    measurementId: 'G-WE9FTRPDD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6IQJDiI-MqvwRnb-Txsgio6CF2S_gCWs',
    appId: '1:195576479889:android:7bf9bea137ded46d10bf30',
    messagingSenderId: '195576479889',
    projectId: 'kebab-and-ploff',
    databaseURL: 'https://kebab-and-ploff-default-rtdb.firebaseio.com',
    storageBucket: 'kebab-and-ploff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmTmfzFcSVA96Yzh0VtPIJFVbuyKriWos',
    appId: '1:195576479889:ios:a1e54fb4485469fb10bf30',
    messagingSenderId: '195576479889',
    projectId: 'kebab-and-ploff',
    databaseURL: 'https://kebab-and-ploff-default-rtdb.firebaseio.com',
    storageBucket: 'kebab-and-ploff.appspot.com',
    iosBundleId: 'uz.abduraimov.kebabAndPloff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmTmfzFcSVA96Yzh0VtPIJFVbuyKriWos',
    appId: '1:195576479889:ios:c50571bb914cff1510bf30',
    messagingSenderId: '195576479889',
    projectId: 'kebab-and-ploff',
    databaseURL: 'https://kebab-and-ploff-default-rtdb.firebaseio.com',
    storageBucket: 'kebab-and-ploff.appspot.com',
    iosBundleId: 'uz.abduraimov.kebabAndPloff.RunnerTests',
  );
}
